# ================================================================= #
#         _              _             _   _   _          _         #
#        / \     _   _  | |_    ___   | \ | | (_)   ___  | | __     #
#       / _ \   | | | | | __|  / _ \  |  \| | | |  / __| | |/ /     #
#      / ___ \  | |_| | | |_  | (_) | | |\  | | | | (__  |   <      #
#     /_/   \_\  \__,_|  \__|  \___/  |_| \_| |_|  \___| |_|\_\     #
#                                                       by Seltrox  #
# ================================================================= #

# ============ Important ============ #
# The placeholders are: {PREFIX}
# If you set BungeeCord on true you have to set your MySQL login data
# You can see all item ids on https://minecraft-ids.grahamedgecombe.com
# You can see all colors on https://wiki.ess3.net/mc/
# ============ Important ============ #

# ============ General ============ #
prefix: "&aAutoNick &8»"
noPermission: "{PREFIX} &cYou don't have permission to do that!"
bungeecord: false
nickOnThisServer: false
permission: "autonick.nick"
adminPermission: "autonick.admin"
changeSkin: true
changeTabname: true
tabName: "&6Premium &7» &6{NICKNAME}"
changeChat: true
chatFormat: "&6Premium &7» &6{NICKNAME}&7: &f"

# This means that users can choose their own nickname with /nick <name>
chooseOwnNick: false
ownNickPermission: "autonick.ownNick"
tooManyChars: "{PREFIX} &cPlease choose a username with a maximum of 16 chars"
tooShort: "{PREFIX} &cPlease choose a username with a minimum of 3 chars"
choosedOwnName: "{PREFIX} &cYou can't choose your original name!"
# ============ General ============ #

# ============ Gui ============ #
nickGui: false
guiTitle: "&8» &aAutoNick"
# ============ Gui ============ #

# =========== Items ============ #
NickItem: true
NickItemSlot: 5
NickDelay: true
NickDelayTime: 3
MessageOnDelay: true
DelayMessage: "{PREFIX} &cYou have to wait before you can use this item!"

ItemIDActivated: 421
ItemNameActivated: "&aAutoNick &7» &aActivated"
ActivateMessage: "{PREFIX} &aActivated AutoNick!"
NickMessage: "{PREFIX} &7You are now nicked as &4{NICKNAME}"

ItemIDDeactivated: 421
ItemNameDeactivated: "&aAutoNick &7» &cDeactivated"
DeactivateMessage: "{PREFIX} &cDeactivated AutoNick!"
UnnickMessage: "{PREFIX} &7You disabled your nickname!"
# =========== Items ============ #

# ============ MySQL ============ #
Host: localhost
Database: myDatabase
Username: myUsername
Password: myPassword
TableName: AutoNick
# ============ MySQL ============ #

Skins:
  - e9013c2f-da01-425f-a48b-516f55e94386
  - 8d05a5ec-100b-4914-8e5f-4fe434b27393
  - d923f435-7061-46d3-8b2e-bbb00d2d7efc
  - e342d64d-78c3-4aae-b075-ae5acc06e487
  - 90ed7af4-6e8c-4d54-824d-e74c2519c655
  - 48eec768-39d7-4df7-93ae-b64adcb2061a
  - d7900636-758f-406d-be9e-9d92cfa80b59
  - 9f1dce8a-e880-466c-9cf8-2e7ca55a1acb
  - 627f0f0b-9ede-4682-abe4-00114eabcc8a
  - 7bc638a8-dfcd-4496-8fc1-9481421f8a3b
  - 30e51afa-d8a1-4ddd-87b4-b155fc7ea5ac
  - 07ce633c-0ca4-4e6a-90d7-3d3600f35f1d
  - 1ecb9a6f-36ed-45b7-bb50-84a2b5ce147c
  - c6e32ac4-a4af-4973-982e-5010b800aadc
  - a8a08aea-987c-466d-8fed-2149798e3e1f
  - c21f069b-137c-4992-8edc-e1a12995ff0f
  - 3d08f3e7-e534-4866-863d-26537ed33002
  - c7fddb9a-adfd-4be3-b326-d700df252e88
  - 79376253-7ec9-46d5-bad2-f38e338342d9
  - 020ea2e2-f143-4e33-b777-e2dd66d510f0
  - 3b7374c2-6119-40ec-baaa-17838f28741d
  - f5716b6d-0899-431c-8e38-6add00447760
  - 597d169a-a685-4029-b2aa-0cae06114f84
  - c15e5087-f701-4c03-8ee8-af5b8cc96729

Names:
  - 0Zero0
  - 2Old4You
  - 5k337
  - 5xan
  - 13sg
  - 270midnight
  - 9001RageQuits
  - Aalglatt
  - Aaroncvx
  - ABCCOOL
  - AchtungIchHacke
  - adamofire2
  - AdidasDaddy
  - AdidasMommy
  - Adminkind
  - Adoxx
  - aerkake
  - AFK_Styler
  - AirFusion
  - AJD25
  - ajs111
  - AkushimaTenshi
  - Alec13
  - Alienate
  - Alkoed
  - alle28
  - AmazingHuh
  - Angelique001
  - AppAx1
  - Aquaah
  - Aqualro
  - aranamor
  - Arkan24
  - Arrbok
  - Arrrg
  - AshrafAnsari
  - asona56
  - AstraDE
  - Astroweeb
  - atomic7732
  - awesomenick01
  - azgoo
  - azgoo
  - bacardee
  - Bademind
  - BadixMitxx
  - baka245
  - BambusMeister
  - BananaHD
  - BananaHD
  - Barbarian22
  - bast_e
  - BearExplosive
  - BedwarsPlayer
  - Ben952
  - bennstone
  - BEnT_uP
  - bestmobbin
  - Bigwinner
  - Billybobjoepants
  - BimKroate
  - BioShock_Rules
  - Blanzer
  - blar210
  - blaze42
  - Blimm
  - Bloodnight
  - BlueCar15
  - Blueline78
  - BluePixl
  - Bob-Omb
  - bombmaker13
  - BoneHunter
  - bosky2102
  - brain_knight
  - Brendan170
  - brent8
  - BrickGaming_GHG
  - broswen
  - Brucki
  - Btrpo
  - bubbyboytoo
  - Buecher
  - buster88
  - buy2k8
  - ByMelone
  - byPizza
  - by_Txm
  - bzoro1
  - CageBomb
  - camcar1
  - CandyRaid
  - Canedis
  - Capt_Danger_
  - Carmelpoptart
  - CatchAGoldfisch
  - catlover2011
  - cbauer1127
  - cchuck
  - cejj99
  - Chacumbe
  - Chan14551
  - chantiiii
  - chase132
  - cherle
  - Chicken500
  - chipandew
  - ChowderBowl
  - christionvork
  - Chzydeath
  - cjoli
  - clara_silver
  - Clawhauser
  - Cli3ntmods
  - clone01
  - CobraEvolved
  - coco113
  - Cocolei
  - ColdNovemberRain
  - colonetrip
  - consoso
  - cookie10
  - CoolBlueJ
  - coolwalker
  - cougar88
  - cruyff14
  - cupcakes_rock
  - cyaloser
  - dabiiiii
  - DaBomb
  - DarkRiderHD
  - DarkShadow
  - DarkStar
  - darkwalker247
  - Darvince
  - DasAbstauber
  - DasDevHorn
  - DaSnipeKid
  - DasSkyWarsPlugin
  - David_355_
  - Dawnofdusk
  - DA_SWAMPMONSTA
  - Dedetv
  - DeepDarkSamurai
  - DefaultAsAwesome
  - demon1972
  - demon1972
  - DerInvisClient
  - DerPedoMichi
  - DerZockerHD
  - Der_Uli
  - destekk
  - De_n00bWOLF
  - diamondhand146
  - DiegoSxnpai
  - DilaraPvP
  - DirtDog
  - DivinityV2
  - domthebom123
  - DontStealMyBacon
  - doozey
  - Dqrk
  - Draconus
  - DragonGamer03
  - dragonsX_
  - Dreadcor
  - Droqen
  - Dylanf3
  - EckigePizza
  - Edison94
  - einLauch
  - Elias_SVS
  - ElliLaudin
  - Em0srawk
  - Endercrafter19
  - enderfemale
  - Entophobia
  - Erak606
  - ErdoGamer
  - ERW2005
  - Estential
  - ezlikespie
  - F0R1
  - Fabiiaan
  - faloxx
  - farrar1
  - FaTaLwassap
  - FaxenWilly
  - FeelingLow
  - Feylyx
  - Fiorensa
  - fire3232
  - Firebow
  - firehawk729
  - Firestix
  - Fixin
  - Fizzy
  - Flipponator
  - Flitzeli
  - For_the_lolz
  - FoxHound42
  - fredddi
  - Funder_HD
  - G0DAce
  - GabrielLP
  - Gail102
  - GalaxyStore
  - GamePlayerYT
  - GamingChanging
  - GamingHD
  - GAWhay
  - GeckoppxHD
  - geez
  - georgeyves
  - GGGGGGA
  - GGPlayer031
  - Gmanda
  - gnomar97
  - goodatthis123
  - grafffuj_HD
  - GreenSoldier
  - grox19
  - Guardian_Gamer_
  - GucciGangOnTop
  - haltyoudoglovers
  - Hannes81
  - hansjoegl
  - harry0214
  - Haxolina
  - HelloToBob
  - HeyItzLogiii
  - Hottii
  - HuhHahLolly
  - HuhHahPika
  - Hydra344
  - Icebreaker_18
  - IchLiebeWeichEi
  - iEmreYT
  - iHxveLxgitAim
  - iiTzWho
  - ILikeMeBetter
  - ImInsane
  - ImWxntedJr
  - Incate
  - Incredible
  - Indicate
  - InTeleKtuElleR
  - ItsFrozenLP
  - Iverox
  - I_am_Save
  - J0ker_
  - JaffaHunter
  - Jakoob__
  - Jamikoko
  - Jax4321
  - JayBee142466
  - Jboy2015
  - Jesha
  - JesusoChristo
  - JoelPlayMC
  - JojoZ1
  - joschiiiTv
  - joshmc
  - Josiii_
  - JRyno
  - Juco29
  - JungYoonsoo
  - JustDavid
  - JustinLP
  - JustYouDad
  - jutske
  - kantra
  - KashyyykScout
  - KevinHDLP
  - KillerPlant
  - Killsh0t
  - KinnajF
  - Kitsniped
  - Kokosnuss2000
  - Koyl
  - Krankenhaus
  - kritzel12
  - kuhler
  - kuqy
  - KuruKuruGuy
  - KyoDemer
  - LaraaGb
  - lari1
  - leonardodragon
  - Leostereo
  - Leviou
  - LINULP
  - LisamagMax
  - LittleKnow
  - LMMN
  - LokiDarkfire
  - lolzlord55
  - Lones02
  - Luvitus
  - macejoe
  - Madisonwilleatu
  - Mahaloo
  - MalexPVP
  - Malpus
  - mangadj
  - Mangle_mag_suses
  - manu75176
  - marett
  - MarsMaus
  - Marv1n
  - Marvin361
  - Mayahem
  - MayoInstrument
  - MegaDev
  - megalennie1
  - MegaLP
  - Meltryl
  - Meman5000
  - MercuryPlayer
  - Messy_Turkey
  - mgk103
  - milk1e
  - milkyyy_
  - Mimo_the_Cat
  - MinecraftMasterz
  - MinecraftMasterz
  - MineMan_620
  - MisterModerator
  - MlgLucasHD
  - mmerlin
  - moleman
  - moshi01
  - MrGreenEye
  - MrHudi
  - MrTreciall
  - Muro45
  - Myapika
  - Napalm_Bomb
  - NebeligesGottaim
  - needsomehugs
  - Neil_Snape
  - Nekora
  - Nekros
  - nessling
  - Neuseeland
  - NewtonLurch
  - nextDoor
  - NightScope
  - Niki2007
  - niks
  - NinjaCrafter3
  - NoahWeasley
  - Nomnomguy
  - nonatz
  - NovaxMind
  - Novolu
  - nukerman
  - Obilara
  - OmnipotentBeing_
  - OneHappyIgloo
  - onlygame
  - OpelSpeedster
  - OprahChrist
  - OrtStefan2007
  - Pancakes
  - PAnikDesigns
  - papthedog05
  - PaulPauli
  - PaulZocker
  - Paysen100
  - PepsiProduct
  - percal
  - perryplat98
  - perryplat98
  - PhantomPlay3r
  - Phyle11
  - Piepsi99
  - pigman21
  - PillowTalk
  - pipola
  - PlayToWin
  - PleaseDoesItNot
  - PokeGoPlayer
  - pokemon_pie
  - Polak2004
  - pompmaker1
  - pongolongo
  - porty101
  - qodaki
  - qodPanda_
  - Quakente07
  - QuickScope
  - qunex_
  - qxvl
  - Radler_zockt
  - RainbowBeauty
  - RandomIdoit
  - ravenhn
  - rawn
  - RazerLp
  - Readshift
  - RealdogeMC
  - Real_Crafter
  - Redwild10
  - REGODY
  - rektusio_
  - Reusomeyang
  - Revary
  - Roachiv
  - robbekes
  - robdee
  - robdee
  - Robekh
  - RoboboyLittle
  - robotronic
  - Rochambo
  - roebuck
  - RtYyU36
  - rumblefish
  - rumblefish
  - runiiii
  - runnerman1
  - runthistown
  - runthistown
  - rutetid
  - ry22an
  - Rybeez55
  - rywyn
  - Sahneboi
  - sakux
  - saltynessy
  - saltytiny
  - sam444
  - sambridger
  - sammydog1997
  - SavageClown
  - schaun1998
  - SchinkenLP
  - Schmoople
  - SchoolHDLP
  - Scr1bble
  - Scramii
  - ScrooLewse
  - scyp10
  - Seasyy
  - SechsMitDir
  - sellbram
  - semoyu
  - semoyu
  - shak1145
  - shinazu
  - ShinHyorin
  - shotgunpaul
  - silverboyp
  - Singular
  - Sitek
  - Sk11lsT3R
  - Skeepy
  - Skiggoo
  - SkillerLP
  - Sky_Flow
  - slim08
  - SnailYT
  - Snerus
  - Sniperzz
  - SongsLP
  - Soulix
  - SoulManGT
  - Sp7ash
  - Space_Walker
  - SpeedyAstro
  - speeeder86
  - SpigotEU
  - spikey123
  - spin810
  - SporkStealer
  - spykey123
  - Squeez
  - StarWarsTV
  - stickzer0
  - Stimmy
  - StoneHD
  - StrawberryShake
  - Stuk
  - sureynot
  - sweenyb
  - Syfaro
  - Synchrophi
  - SyntaxDev
  - Taani
  - Taitos
  - tapout10
  - tapout10
  - tapout10
  - TaqticalNeysto
  - Techdolpihn
  - TehEPICD00D
  - TEH_CATFACE
  - TerenceKoj
  - thamightybobo
  - TheAisi
  - TheChillPixel
  - TheCraftR
  - TheDarkMine
  - TheEpicBlock
  - thegrees
  - TheKingOPower
  - theSero
  - thetangledhand
  - The_Other_Retard
  - The_Redstonegeny
  - The_SnowBro
  - ThomasHD
  - Tilan
  - timchen
  - timii
  - timonde
  - timperi
  - TokyoGhoulGirl
  - TotallNasty
  - ToxicPvP
  - tragisch
  - Traveler
  - Travuersa
  - tubbsy_
  - TunaTunca
  - ukcats
  - ultimatebag
  - UmpaCrumpa
  - Univers1Master
  - UnknownKise
  - Unlegit_King
  - UnmaskedDavid
  - Unsuccessfulness
  - ur_dead
  - Usernamenotfound
  - Usoka
  - v1per93
  - Vacien
  - ValkonX11
  - vellyamy
  - verbel
  - vielseitig
  - viking58
  - vlnpixde
  - WalkingDragon
  - waltisawesome
  - Warior135
  - WarSyndrome
  - WasGehtSieDasAn
  - Wazdorf
  - wefuu
  - WhenxHD
  - wilde_katze
  - wildii
  - Wittlededittle
  - WolfS4sha_
  - Wolf_Gamer_123
  - wolpaladin
  - Wondwi
  - WoodLP
  - woowoo678
  - Wubdo
  - WWTV
  - xAzura
  - Xboy001
  - xd_Yupsifuchsi
  - xErenPvP
  - XerXers300
  - xF3RR0
  - xGravity
  - xMysteries
  - xRainimator
  - xTaxxel
  - xXDasInternetXx
  - xXNiclasPvPXx
  - xxxTenreptix
  - x_kyle_x
  - X_Paragon_X
  - Yad
  - yazory
  - yeetwol
  - YesChopp
  - YouAreToeZForMe
  - yourescared
  - YoutubeProHD
  - Zakhep
  - zAngel_
  - ZaubererFuge839
  - zCitex
  - zebbe9999
  - ZerolHD
  - Zetram
  - Zeynee
  - zFoxyCW
  - Zkyo
  - Zoropie5
  - zSerix
  - zSkyFuxnkyZz
  - zUnleqiitAppel
  - zVxqian
  - zZeus_
  - _889ms
  - _BukkitPvP_
  - _DenizTR_